### ISSUE TITLE
Excellent！Would you like to provide us a windows version? Thanks!

### ISSUE THREAD

**Issue by zhangfq-chemistry** [geodavic/poly_factor#9]

**Comment by zhangfq-chemistry** [comment]
I have difficulty to compile your code under windows. Or, please remove the dependence on gmp, mpc and mpfr. Thanks!

**Comment by geodavic** [comment]
Thanks for the feedback! Unfortunately the GMP libraries are requirements. What tools are you using to compile the code in Windows?
